# according to https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#issue_comment
name: Benchmark PR

permissions:
  contents: read
  pull-requests: write

on:
  issue_comment:
    types: [created]

jobs:
  runBenchmark:
    if: |
      github.event.issue.pull_request != null && 
      contains(github.event.comment.body, '/benchmark')
    name: Criterion benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
      - name: Compares PR branch to target
        uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{ github.event.pull_request.base.ref }}
          benchName: "bench_archive"
          token: ${{ secrets.GITHUB_TOKEN }}