# according to https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#issue_comment
name: Benchmark PR

permissions:
  contents: read
  pull-requests: write

on:
  issue_comment:
    types: [created, edited]

jobs:
  runBenchmark:
    if: |
      github.event.issue.pull_request && 
      contains(github.event.comment.body, '/benchmark')
    name: Criterion benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # compares pull request branch to target, which is its base reference
      - uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{ github.event.issue.pull_request.base.ref }}
          benchName: "bench_archive"
          token: ${{ secrets.GITHUB_TOKEN }}